spring.application.name=rest

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/Office
spring.datasource.username=root
spring.datasource.password=mysql@123Karanam


spring.thymeleaf.cache=false

logging.level.org.springframework.jdbc.core.simple=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
